fwm:fwm_menu.o fwm_func.o 
	gcc -o ../Bin/fwm ../SRC/fwm_menu.c ../SRC/fwm_func.c
        

fwm_menu.o:../SRC/fwm_menu.c
	gcc -c ../SRC/fwm_menu.c 


fwm_func.o:../SRC/fwm_func.c
	gcc -c  ../SRC/fwm_func.c 

clean:
	rm *.o

